### ISSUE TITLE
Delete and discussion request 

### ISSUE THREAD

**Issue by Philosoft** [phptodayorg/php-must-watch#11]
IMHO `My Take on PHP - Fabien Potencier at dotScale 2014 [18:19]` is noninformative talk. At first 5-8 minutes Fabien goes about how we/he love php as a platform and hate it as a language. Then blah blah blah PHP is designed to die after one request. How would it be wonderful with wonderland with unicorns if we can bootstrap files and classes, keep persistent DB connection etc etc save heck of a lot of time on that and improve performance up to 15-20x faster. PHP Application Server. We need it, just like other languages - Java, Python, even JavaScript (with Node.js / io.js). Hey, we have something like that [marcj/php-pm](https://github.com/marcj/php-pm).

So it's a practycally summary of whole talk. My point - waste of time, noninformative, can be replaced with `php is designed to die after handling one and only request. Applications servers live on to serve infinite number of request without problems with memory, bootstraping, db connections and so on. Application servers are faster. We need one for us.` See in [marcj/php-pm](https://github.com/marcj/php-pm) direction as example and starting point.

**Comment by seyfer** [comment]
For me it was very interesting talk. It less technical, but more political and in particular gives us approach about PHP future. He told in his talk, that all became better with PHP and ecosystem.

Also I sent this talk to some my friends non-PHP programmers, because they are PHP haters and this talk shows them, that's it's all gonna be okay with PHP and it's have good develop progress.

I disagree with to remove this talk, it should be kept.

Fabien Potencier told and give example with Symfony and https://github.com/marcj/php-pm, but he also told, that frameworks not optimized to run in this enviroment, and he gonna work with that. That was a major point.

Here is the link with benchmark tests from Fabien talk
http://marcjschmidt.de/blog/2014/02/08/php-high-performance.html

And also https://github.com/marcj/php-pm have link to this page in Readme.

`
Fourth, even though ReactPHP gives us the ability to write asynchronous code, most libraries (including Symfony) aren't written this way.
`

**Comment by Philosoft** [comment]
that's why I call out to discuss) From that perspective, I think we really should find more concrete talk on that topic, sure there must be one.

on that specific talk - I do not deminish its value as it is, only that - it too long and provides too few facts, repos, benchs, articles, research etc on it's topic. it really could be compressed down to 5 min tops

**Comment by shameerc** [comment]
Thanks @Philosoft, @seyfer for your feedbacks. 
I too agree that this is not really a must watch for PHP developers, but included this for the political reasons. So I think it's better to keep it, may be some people will find it useful :)

**Comment by Philosoft** [comment]
ok =)
